### ISSUE TITLE
Price difference calculation error

### ISSUE THREAD

**Issue by boo-code** [christophermallory/magento2-freeshipping-progress-bar#3]
![image](https://user-images.githubusercontent.com/65190196/115249052-8827b700-a128-11eb-8f65-1c435dbd275b.png)

**Comment by gino2014** [comment]
Hello,
just installed at M2.4.3-p3 Shop and can confirm the price difference. We are showing price with tax and extension seems to calculate price without tax.
![Bild_2022-11-03_101647874](https://user-images.githubusercontent.com/6517231/199684456-8dc11a49-9dfe-4377-ae80-649b2bc38467.png)
