### ISSUE TITLE
Storeview based calculation not working

### ISSUE THREAD

**Issue by musabatas** [christophermallory/magento2-freeshipping-progress-bar#4]
I have installed and configured this extension on 2.4.3-p1 installation with multistore and multicurrency. Unfortunately, the calculation does not work with multicurrency. And I added the total price thresholds per store view, also that is not worked.

**Comment by amcguireweb** [comment]
It's missing the SCOPE_SCORE parameter everywhere in the ViewModel.

add `, \Magento\Store\Model\ScopeInterface::SCOPE_STORE` to all calls to the system configuration inside **ViewModel/Cart/ProgressBar.php**.

For example, this:
`$this->scopeConfig->getValue(self::CHECKOUT_CART_XML_CONFIG_PATH . 'use_freeshipping_method_config')
`
Becomes this:
`$this->scopeConfig->getValue(self::CHECKOUT_CART_XML_CONFIG_PATH . 'use_freeshipping_method_config', \Magento\Store\Model\ScopeInterface::SCOPE_STORE)`.

**Comment by christophermallory** [comment]
I updated the release to include the latest code
