### ISSUE TITLE
how 0Works on any page

### ISSUE THREAD

**Issue by lee-xu** [christophermallory/magento2-freeshipping-progress-bar#6]
This is exactly the functionality I need. But I want to show it at the top of the page. It only works on the cart page, I think it will work on any page.

**Comment by christophermallory** [comment]
You would have to restyle it but you could reference my block and place it anywhere you'd like. My other extension works on most pages - See this link for how the viewModel is referenced to show on each page: https://github.com/christophermallory/ChrisMallory_PromoBanner/blob/master/view/frontend/layout/default.xml
