### ISSUE TITLE
frontend view error: show only for enabled countries

### ISSUE THREAD

**Issue by beendeluxe** [christophermallory/magento2-freeshipping-progress-bar#7]
Hey, 

the extension is nice and we want to help with our suggestions and bug reports.

As the title shows, there is an issue on frontend. Our Shipping policy says: free shipping over 59 € for Germany. The free shipping method is enabled only for Germany too. 

The extension shows the "Free Shipping" message for other countries too, but it should hide. 

Could you fix it? 

Another thing is, that we would like to show this message also at mini-cart and also at checkout. Doable? 
A Widget to place the message would also be nice. 

Hope it helps.

**Comment by christophermallory** [comment]
Hi @beendeluxe,

I have updated the code to resolve your issue.

For the feature request, please contact me directly via chris@chrismallory.io and I will try to help.
